name: Daily Data Fetch and Commit Workflow

on:
  schedule:  # enable scheduled triggering of workflow
    - cron: '30 16 * * *' # Runs at 4:30 PM UTC (8:30 AM Toronto)
  workflow_dispatch:  # enable manual triggering of workflow

jobs:
  fetch_and_process_data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install pandas requests scikit-learn holidays

    - name: Fetch and Save Data
      env:
        API_KEY: ${{ secrets.API_KEY }}
      run: python fetch_and_save_data.py

    - name: Commit and Push changes
      run: |
        git config user.name 'github-actions'
        git config user.email 'github-actions@github.com'
        git add -f data/test_data_2024.csv
        git commit -m "Auto-update data" -a || echo "No changes to commit"
        git push
