name: Daily Data Fetch and Commit

on:
  schedule:
    - cron: '45 19 * * *' # Runs at 7:45 PM UTC (3:45 PM Toronto time (Standard Time))

jobs:
  fetch_and_process_data:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11' # Specify the Python version you are using

    - name: Install dependencies
      run: |
        pip install pandas requests scikit-learn holidays

    - name: Fetch and Save Data
      env:
        API_KEY: ${{ secrets.API_KEY }}
      run: python fetch_and_save_data.py

    - name: Commit and Push changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add -f data/test_data_2024.csv
        git commit -m "Auto-update data" || echo "No changes to commit"
        git push
